# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\tinference\"\x90\x01\n\x0ePredictRequest\x12\x39\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\'.inference.PredictRequest.FeaturesEntry\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"<\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x03(\x02\x12\x15\n\rmodel_version\x18\x02 \x01(\t2T\n\x10InferenceService\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST_FEATURESENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=27
  _globals['_PREDICTREQUEST']._serialized_end=171
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_start=124
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_end=171
  _globals['_PREDICTRESPONSE']._serialized_start=173
  _globals['_PREDICTRESPONSE']._serialized_end=233
  _globals['_INFERENCESERVICE']._serialized_start=235
  _globals['_INFERENCESERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
